export const InspirationData = [
    {
        img: Insp1,
        name: "Desert king" ,
        price: "1MBT per night" ,
        distance: "2345km away",
        availability: "available for 2 weeks stay",
        rating: StarRating,

    },
    {
		img: Insp2,
		name: "Desert king",
		price: "1MBT per night",
		distance: "2345km away",
		availability: "available for 2 weeks stay",
		rating: StarRating,
	},
    {
		img: Insp3,
		name: "Desert king",
		price: "1MBT per night",
		distance: "2345km away",
		availability: "available for 2 weeks stay",
		rating: StarRating,
	},
    {
		img: Insp4,
		name: "Desert king",
		price: "1MBT per night",
		distance: "2345km away",
		availability: "available for 2 weeks stay",
		rating: StarRating,
	},
    {
		img: Insp5,
		name: "Desert king",
		price: "1MBT per night",
		distance: "2345km away",
		availability: "available for 2 weeks stay",
		rating: StarRating,
	},
    {
		img: Insp6,
		name: "Desert king",
		price: "1MBT per night",
		distance: "2345km away",
		availability: "available for 2 weeks stay",
		rating: StarRating,
	},
    {
		img: Insp7,
		name: "Desert king",
		price: "1MBT per night",
		distance: "2345km away",
		availability: "available for 2 weeks stay",
		rating: StarRating,
	},
    {
		img: InspImg8,
		name: "Desert king",
		price: "1MBT per night",
		distance: "2345km away",
		availability: "available for 2 weeks stay",
		rating: StarRating,
	},
];